[package]
name = "dot-screen"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
image = { version = "0.25.10", default-features = false, features = ["jpeg"] }
objc2-core-graphics = "0.3.2"
screencapturekit = { version = "10.0.3", features = ["macos_14_0"] }
thiserror = "2.0.20"
